version: '3.7'
services:
    rabbitmq_adapter:
        restart: always
        image: 'faucet/event-adapter-rabbitmq:1.9.47'
        volumes:
            - '${POSEIDON_PREFIX}/var/run/faucet:/var/run/faucet'
        environment:
            FAUCET_EVENT_SOCK: '1'
            FA_RABBIT_HOST: 'rabbit'
            FA_RABBIT_PORT: '${FA_RABBIT_PORT}'
            FA_RABBIT_EXCHANGE: '${FA_RABBIT_EXCHANGE}'
            FA_RABBIT_EXCHANGE_TYPE: '${FA_RABBIT_EXCHANGE_TYPE}'
            FA_RABBIT_ROUTING_KEY: '${FA_RABBIT_ROUTING_KEY}'
        networks:
            - poseidon
    faucet_certstrap:
        restart: on-failure
        image: 'cyberreboot/faucet-certstrap:latest'
        build:
            context: helpers/faucet/certstrap
            dockerfile: Dockerfile
        volumes:
            - '${POSEIDON_PREFIX}/opt/poseidon:/opt/poseidon'
        command:
            - /opt/poseidon/local/faucetconfrpc
            - faucetconfrpc
    faucetconfrpc:
        restart: always
        image: 'cyberreboot/faucetconfrpc:v0.6'
        environment:
            PYTHONUNBUFFERED: '1'
        volumes:
            - '${POSEIDON_PREFIX}/opt/poseidon/local:/local'
            - /etc/faucet:/etc/faucet
        networks:
            - poseidon
        command:
            - --key=/local/faucetconfrpc/faucetconfrpc.key
            - --cert=/local/faucetconfrpc/faucetconfrpc.crt
            - --cacert=/local/faucetconfrpc/faucetconfrpc-ca.crt
            - --host=0.0.0.0
            - --config_dir=/etc/faucet
networks:
    poseidon:
        driver: overlay
